language: python
python:
    - "3.8"
install:
    - pip install coverage
    - pip install ./
script:
    - coverage run -m unittest discover -s WestCoastAD/test -p '*_test.py'
after_success:
    - bash <(curl -s https://codecov.io/bash)
